### PR TITLE
update CI and .node-version to use node 16.0.0

### PR DESCRIPTION
**Pull request by pankona**
Refs: https://github.com/mobu-of-the-world/mobu/issues/105

## Updates

- Introduce node 16.0.0
  - Update CI to use node 16.0.0 as well

### CODE REVIEW

**Review by kachick — APPROVED** [review]
* The diff looks applied changes only for `Test and Lint`. Where is the actual deploy flow of this repository? 🤔 
* And I think testing 16.x only is enough, if the deploy engine is using 16.x. But I don't have strong opinion for that.

**Comment by pankona** [comment]
@kachick 

This pull requests updates `.node-versions` to use 16.x. Netlify respects `.node-version` file.

**Comment by pankona** [comment]
@kachick 

As addressed in https://github.com/mobu-of-the-world/mobu/pull/108/commits/71c7664769769d70cf2a368b310e1642b814ebc9 , I dropped node 14.x support from linting/testing

**Comment by pankona** [comment]
go bold

**Comment by kachick** [comment]
Thanks for your all of works! 🎉

**Pull request merged**
