### PR TITLE
[RFC] shorter code by reducing bucket relay

### PR DESCRIPTION
**Pull request by pankona**
## Updates

- reduce buckets relay by using
  - props object
  - IntrinsicElements["button"]
  - reduce redandunt css

### CODE REVIEW

**Comment by pankona** [comment]
@kachick 

How about this?

**Comment by pankona** [comment]
Looks good

**Comment by kachick** [comment]
Sorry to late review! Reducing props relay is basically good decision, I think 👍

**Comment by pankona** [comment]
@kachick 

Thank you!! 💪

**Pull request merged**
