### PR TITLE
Introduce a feature which enable to ring a bell when an interval comes

### PR DESCRIPTION
**Pull request by highwide**
Hi, this is my first pull request for mobu.

## Purpose
I and my colleagues use mobu very often in mob-programming.
But I feel only one pain on this product.
It's that we can't notice a finishing of an interval.

So today, I'd like to introduce a feature which enable to ring a bell when an interval comes.

## Image
Screen Shot 2021-04-04 at 20 50 48

## notes

* The mp3 file was downloaded here: https://freesound.org/people/danarobinsondesignsgmailcom/sounds/377639/
  * This audio is licensed under Creative Commons 0.

### CODE REVIEW

**Comment by kachick** [comment]
Oh great feature is coming... @pankona @kachick should immediately check this proposal!

**Review by kachick — APPROVED** [review]
I have checked the behaviors on https://deploy-preview-79--mobu-waiwai.netlify.app/

* Enabled the `bell` box making sound `ding`!
* Disabled it does not sounds anything.

Looks good! Thank you!

スクリーンショット 2021-04-04 21 27 01

**Comment by pankona** [comment]
Screenshot_20210404-213018

It works fine on mobile as well. Great!

**Review by pankona — APPROVED** [review]

**Comment by pankona** [comment]
LGTM!!

**Comment by highwide** [comment]
@kachick @pankona Thank you for quick reviewing 🙏 
I'm honored that I could contribute this wonderful product 🎉

**Pull request merged**
