### PR TITLE
Integrate dprint to enable `no-mixed-operators` in eslint

### PR DESCRIPTION
**Pull request by kachick**
dprint vs prettier
---

Both have the strongness. Prettier has strong opinion and huge community, and looks stable behavior in these days.
dprint is pluggable, configurable and super fast ⚡.

Why dprint now?
---

Because prettier does not provide some options with their opinion.
A most negative to me is prettier/prettier#187.
I strongly agree eslint rule [no-mixed-operators](https://eslint.org/docs/latest/rules/no-mixed-operators).
At least, added parenthesis should not be removed by formatter if it was coder wanted.
However no option exists when using prettier.
It is a blocker to me especially developing around timer logics as #486.

Dprint is frequently developing now. So some style can't be adjusted to prettier does well.
But I 👍 for their decisions and I think it is enough ready to be used.

How
---

This PR does not perfectly drop prettier, it still used in HTML, CSS and YAML. Dprint runs on TypeScript, JavaScript, JSON, Markdown.
And needed to enable renovate to upgrade their plugins.

Configure
---

Some choice exists, however I have chosen minimum one.
If you strongly want enable some options, look at https://dprint.dev/config/ and https://dprint.dev/plugins/typescript/.
I can't reproduce 100% prettier behaviors even I have tried with some options in few hours.

Refs
---

🇯🇵 

* http://var.blog.jp/archives/86088118.html
* https://github.com/kachick/times_kachick/issues/164
* https://github.com/kachick/times_kachick/issues/168
* https://github.com/kachick/times_kachick/issues/171

### CODE REVIEW

**Comment by pankona** [comment]
I think it is not necessary to reproduce prettier's behavior if we use dprint. I like default configuration. If possible, I don't want  to see any configuration files at all. I like zero config. If we choice dprint, let's use it without any configuration. minimal.

**Review by pankona — APPROVED** [review]
Let's use it!

**Comment by kachick** [comment]
>zero config

https://github.com/dprint/dprint/issues/413 exists. However I think choosing dprint means to need some config because of the configurable tool direction as we use eslint config.

**Comment by kachick** [comment]
Thanks for your approvable!

**Comment by kachick** [comment]
FYI: Microsoft is now using dprint for their TypeScript repository https://github.com/microsoft/TypeScript/pull/54820

**Comment by kachick** [comment]
>This PR does not perfectly drop prettier, it still used in HTML, CSS and YAML.

Completely replaced in https://github.com/mobu-of-the-world/mobu/pull/1487

**Pull request merged**
