### PR TITLE
Trivial English fixes

### PR DESCRIPTION
**Pull request by ujihisa**

### CODE REVIEW

**Review by kachick — APPROVED** [review]
LGTM, thanks for your first contribution 👍 
I think this is generated by create-react-app https://github.com/facebook/create-react-app/blob/7e4949a20fc828577fb7626a3262832422f3ae3b/packages/cra-template-typescript/template/README.md

So how do you think to create PR for the original project? 😄

**Comment by pankona** [comment]
Sweet changes! Thanks! @ujihisa

**Review by pankona — APPROVED** [review]

**Comment by ujihisa** [comment]
> So how do you think to create PR for the original project? :smile:

Done! ttps://github.com/facebook/create-react-app/pull/10763

**Comment by ujihisa** [comment]
> So how do you think to create PR for the original project? :smile:

Done
https://github.com/facebook/create-react-app/pull/10763

**Comment by kachick** [comment]
Oh it is great work! You saved a lot of people from this issue! And this PR is the origin of the fix. It is honored for `mobber` as me 😄

**Pull request merged**
