### PR TITLE
Introduce dark theme with prefers-color-scheme media query

### PR DESCRIPTION
**Pull request by ravelll**
This PR adds a dark theme with [prefers-color-scheme media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).
Internet Explorer doesn't support the query, but I think it doesn't matter because this application is a cutting-edge service.

image

This change doesn't mean that adds a feature to toggle themes to light or dark.
Theme be applied to be fit with OS's appearance configuration.
I will try to add a feature to toggle themes later. (Of course, anyone can try it 🤓 )

What do you think about this direction? Thanks.

### CODE REVIEW

**Comment by pankona** [comment]
Screenshot_20210524-235349

it works!!

**Comment by pankona** [comment]
@ravelll 

Thank you for your great contribution!
It seems there's some conflict. Could you please ease them?

**Comment by ravelll** [comment]
I accidentally add some style to disabled buttons. Please wait for removing them 🙏

**Comment by ravelll** [comment]
@pankona I resolved the conflict and fixed some styles. Could you review this again?

**Review by pankona — APPROVED** [review]

**Comment by pankona** [comment]
It seems really good...!

**Comment by pankona** [comment]
@kachick 

Could you please try it? It is amazing!

**Comment by kachick** [comment]
>Internet Explorer doesn't support the query, but I think it doesn't matter because this application is a cutting-edge service.

スクリーンショット 2021-05-27 8 59 26

Basically agreed. If I may add a few things, we might provide `Enterprise Edition of mobu` when it might be cared. But this repository is the cutting-edge, yes. So we can ignore Internet Explorer 👍 

>This change doesn't mean that adds a feature to toggle themes to light or dark.
Theme be applied to be fit with OS's appearance configuration.

Oh... I didn't know the feature...

https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/dark-mode/

スクリーンショット 2021-05-27 9 02 13
スクリーンショット 2021-05-27 9 03 47
スクリーンショット 2021-05-27 9 03 58
スクリーンショット 2021-05-27 9 04 04

Looks worked perfectly!

>I will try to add a feature to toggle themes later. (Of course, anyone can try it 🤓 )

😍 👍 

---

This PR looks `perfect` to me. The change and description are also good 👍 

Resolves #122

**Review by kachick — APPROVED** [review]
Thanks for your great work!

**Pull request merged**
